name: Get Version (Date)
on:
  woworkflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install axios cheerio
      - name: Extract date
        run: |
          node -e "
          const axios = require('axios');
          const cheerio = require('cheerio');
  
          const url = 'https://sigmapatches.coomer.party/';
  
          axios.get(url).then(response => {
            const $ = cheerio.load(response.data);
            const field = $('[title=\'sigpatches\']');
            if (field.length) {
              const href = field.attr('href');  // get the href attribute
              const date = href.split('?')[1];  // split on '?' and take the second part
              console.log(`Date: ${date}`);
            } else {
              console.log('Field with title=\'sigpatches\' not found.');
            }
          }).catch(error => {
            console.error(`Failed to fetch page: ${error}`);
          });
          "
