name: Create Clean SigPatches Release
run-name: ${{ github.workflow }} ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  create-new-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download and unzip
        run: |
          curl -LJO https://sigmapatches.coomer.party/sigpatches.zip
          unzip sigpatches.zip -d /tmp/sigpatches
        
      - name: Clean content
        run: |
          rm -rf /tmp/sigpatches/atmosphere/contents

      - name: Archive files
        run: |
          cd /tmp/sigpatches
          zip -r CleanSigPatches.zip *
          
      - name: Create release
        id: create_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ inputs.version }} /tmp/sigpatches/CleanSigPatches.zip --notes "Latest release of CleanSigPatches zip."
